### ISSUE TITLE
Portal is not responding

### ISSUE THREAD

**Issue by ashepherd** [mmisw/orr-portal#103]
Hi folks, 

Just wanted to check on status of the ESIP COR portal, as it seems to be down: http://cor.esipfed.org/ont#/

**Comment by carueda** [comment]
Thanks for the heads-up ... looking into it right now ...

**Comment by carueda** [comment]
Contacting ECITE as I cannot even access the VM.

**Comment by carueda** [comment]
Many thanks again Adam for the heads-up.  
The ESIP COR is back up now.
