### ISSUE TITLE
terms not resolving properly in mmisw v3?

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#104]
Not sure what the nature of this issue is.

If I go to http://mmisw.org/ont/mmi/platform, I get a list of triples that includes, e.g., http://mmisw.org/ont/mmi/platform/Aeroplane. 

If I click on or enter that term, I get the following error:
```
{
  "msg": "resolveUri: error getting term",
  "error": {
    "error": "error querying uri=http://mmisw.org/ont/mmi/platform/Aeroplane: java.net.ConnectException: https://mmisw.org:10035/repositories/mmiorr"
  }
}

http://mmisw.org/ont/mmi/platform/Aeroplane
URI not found
No ontology registered with this URI
No subject in the triple store with this URI
```

I think it's a valid URI, but not sure what the connection issue is.

I am not logged in, but I think that's a public ontology, so it shouldn't matter.

**Comment by carueda** [comment]
Thanks for the heads-up ... It was a mistake with the configuration related with the sparql endpoint.  Fixed.

![image](https://cloud.githubusercontent.com/assets/556505/26560725/a2c1c04a-446d-11e7-834a-7e72b01352f8.png)
