### ISSUE TITLE
question about 'most recent version' URIs

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#105]
In http://marinemetadata.org/apguides/ontprovidersguide/ontguideconstructinguris#urlversioning we have the following section/text.  Do we ever support the '$' substitution for the version string? I'm guessing not.

```
URLs to Specify the Most Recent Version of an Ontology or Term

It is often the case that a user wants to obtain the most recent version of a given ontology or term. In this case, the version string is replaced by '$'. (The resourceType can never begin with a dollar sign, so confusion is unlikely.) Thus, these requests should obtain the most recent version of the corresponding ontology or term:

http://mmisw.org/ont/mmi/$/platform.owl
http://mmisw.org/ont/mmi/$/platform/moored_buoy
```

**Comment by carueda** [comment]
It was implemented a long while ago, not anymore.

**Comment by graybeal** [comment]
Hey ... it looks like we don't resolve individual versioned ontologies or URIs (any more?), either.

So there's not (any longer?) a way to look up a particular term version?

**Comment by carueda** [comment]
Are you using the `version` parameter? If yes, then it would be a bug.  Give a specific example please.
