### ISSUE TITLE
use of LODE feature

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#106]
If I go to http://mmisw.org/ont/nasa_pace/taxonomy and click on the LODE link, it is only seeing/displaying the header of the ontology. Is that the expected behavior?

**Comment by carueda** [comment]
Unexpected.  Are you noticing this with other entries?

**Comment by carueda** [comment]
Looks like a LODE bug:  I tried with explicit request for an ontology format 

http://www.essepuntato.it/lode/owlapi/http://mmisw.org/ont/api/v0/ont?format=rdf&uri=http://mmisw.org/ont/nasa_pace/taxonomy

and it still only shows the namespace declarations, while the contents of the response to http://mmisw.org/ont/api/v0/ont?format=rdf&uri=http://mmisw.org/ont/nasa_pace/taxonomy looks as expected.

Not closing this yet while we can further confirm.

**Comment by carueda** [comment]
It's actually a bug in the ORR backend: https://github.com/mmisw/orr-ont/issues/52

Will close this one once that is fixed.

**Comment by carueda** [comment]
- Just fixed https://github.com/mmisw/orr-ont/issues/52.
- Since LODE seems to follow content negotiation practices, now the link http://www.essepuntato.it/lode/owlapi/http://mmisw.org/ont/nasa_pace/taxonomy gets dispatched as expected.
