### ISSUE TITLE
Update jQuery to 3.0.0

### ISSUE THREAD

**Issue by lewismc** [mmisw/orr-portal#121]
![screen shot 2018-02-28 at 8 43 13 am](https://user-images.githubusercontent.com/1165719/36800066-72e8311e-1c63-11e8-8dd3-f54df1b187b0.png)

**Comment by carueda** [comment]
Yep, thanks for the reminder!  Hopefully straightforward to do and I'll try it asap.

**Comment by carueda** [comment]
Aa noted in the commit, there's no actual dependency on jQuery, so it was simply removed from package.json
