### ISSUE TITLE
Input elements should have autocomplete attributes

### ISSUE THREAD

**Issue by carueda** [mmisw/orr-portal#122]
Noted by Chrome dev console while logging in:

> Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq)

![image](https://user-images.githubusercontent.com/556505/36811790-df4e0746-1c83-11e8-8be2-5ecb1bb9f755.png)

**Comment by assunluis80** [comment]
This extremly annooying! I don't want autocomplete on my forms. But since Chrome throw these annoying messages, I added autocomplete to all inputs with autocomple=Off, but it still complaining! WTF!

**Comment by IamAlta** [comment]
Ignore it. Those are only warnings.
It's dumb that google does that since all the security and privacy issues these days.

**Comment by jmkh** [comment]
<input type="password" id="password" name="password"  class="login_input  login_input_password" maxlength="16"  autocomplete="current-password" required minlength="6"
                   onkeyup="value=value.replace(/[^\w\.\/]/ig,'')" title="请输入登录密码" placeholder="请输入登录密码">

**Comment by lewismc** [comment]
@carueda is this issue valid or do we close it?

**Comment by carueda** [comment]
I think I entered this thinking that it would be convenient (at least for me) to have this kind of autocompletion in place. But it does look like it might not be generally acceptable. Let's close it.

**Comment by shahrukhaziz** [comment]
Ignore it. Those are only warnings, it will not affect your code, but I think it would be great if you add input autocomplete it will help end user.
<div class="form-group">
                    <label for="title">Email ID</label>
                    <input type="text" class="form-control" id="email" placeholder="Enter Your Email"
                        aria-describedby="emailHelp" email="required" autocomplete="on">
</div>
