### ISSUE TITLE
Capture acceptance of Terms Of Use in new-account setup

### ISSUE THREAD

**Issue by carueda** [mmisw/orr-portal#123]
(As discussed in COR telecon today 5/22/18.)

Such Terms of Use option is part of the configurability/branding of the ORR.   This gets reflected as a link at the top of the ORR page. 

The task here is to complement that display with an explicit prompt to the user to accept such terms at time of account creation.

@lewismc @abburgess @graybeal  FYI

**Comment by lewismc** [comment]
ACK, I've written to staff @ esipfed and will post the feedback here.

**Comment by abburgess** [comment]
Staff is working on Terms of Use.

**Comment by carueda** [comment]
In 3.9.4 the create account dialog looks like this

![image](https://user-images.githubusercontent.com/556505/83209000-068ffa80-a10c-11ea-9d96-c64504980060.png)

(plus the usual recaptcha widget when system configured with such feature.)

**Comment by graybeal** [comment]
@carueda  This addresses the code part but we still don't have any feedback from staff on the terms that I know of. Open a new ticket?

**Comment by carueda** [comment]
Yes, a ticket in some ESIPFed repo would be appropriate
