### ISSUE TITLE
scrolling in Chrome out of control

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#125]
Using Crome on my Mac, when I do a two finger trackpad scroll very slowly in a long list (either the ontology browse page or the list of terms), I can scroll about one full page and then the list takes off, not stopping until it reaches end-of-list. Does not happen scrolling back up the other way, but is very repeatable scrolling down.

Doesn't happen on Safari. Anyone else having this problem?

**Comment by carueda** [comment]
This issue has been there for a very long time.  It will probably be fixed with an upgrade of the underlying library (angular-ui-grid).

**Comment by carueda** [comment]
I'm not seeing this misbehavior in 3.8.7, just deployed for the COR, so closing as fixed.

@lewismc fyi
