### ISSUE TITLE
Increase size of upload data > 10MB

### ISSUE THREAD

**Issue by lewismc** [mmisw/orr-portal#126]
I have been working on generating RDF manifestations of the NASA [Global Reservoir and Dam Database](http://sedac.ciesin.columbia.edu/data/collection/grand-v1/sets/browse) (GRanD v1.01) which results in a two fairly large datasets. One is ~20MB and the other ~130MB.
@carueda what are the chances of us increasing the maximum 10MB for datasets ?
Thanks

**Comment by carueda** [comment]
@lewismc @graybeal 

Those are large datasets.

Anyway, I can increase the size limit for the upload (this [restriction is performed on the backend](https://github.com/mmisw/orr-ont/blob/master/src/main/scala/org/mmisw/orr/ont/app/OntController.scala#L23)).

What limit should I set?

**Comment by carueda** [comment]
BTW, because it's specially relevant, I'll try to also address https://github.com/mmisw/orr-ont/issues/68 for the resulting new ORR version.

**Comment by lewismc** [comment]
For the LDaaS initiative we would be looking to facilitate large RDF datasets with possibly hundreds of thousands if not millions of statements. The hydrography datasets I a working with now will reflect that. For the time being if we could set it at 150MB it would be excellent. Thank you for the quick reply @carueda

**Comment by carueda** [comment]
@lewismc I've just implemented this (with 150M as size limit for uploads -- but this is now configurable), created new docker image, and updated the COR instance.  I'm marking this as resolved.  Please give it a try when you have a chance and let me know.  

*NOTE*:  The docker image is v3.8.0, but the frontend component is 3.7.3, which is the version you should now see on the UI.  (Will try to "resync" the versions next time.)

(btw,  https://github.com/mmisw/orr-ont/issues/68 not addressed yet.)

**Comment by lewismc** [comment]
@carueda thanks for acting on this. When I try to use the frontend WebUI, it still indicates 10MB is upper limit. 
<img width="568" alt="screen shot 2019-01-15 at 1 21 12 pm" src="https://user-images.githubusercontent.com/1165719/51210749-6d6e9400-18c8-11e9-886a-241b846890ff.png">

**Comment by carueda** [comment]
@lewismc Can you email me that 21MB file (compressed) so I can do some local tests?

**Comment by carueda** [comment]
Found the problem.  Will create a new release.
