### ISSUE TITLE
Update lodash and jquery dependncies

### ISSUE THREAD

**Issue by lewismc** [mmisw/orr-portal#127]
Both dependencies are flagged as moderate severity security risks. We need to update these ASAP.

**Comment by carueda** [comment]
ack! ;)

**Comment by lewismc** [comment]
I'm starting work on this.

**Comment by carueda** [comment]
Thanks Lewis, but I already addressed it.  Sorry I didn't know you were planning on working on this. ( There's now  a new docker image, 3.8.3).

**Comment by lewismc** [comment]
Nice thank you
