### ISSUE TITLE
upgrade metadata properties in ORR.

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#131]
Upgrade ORR metadata to follow the advice and properties of Widoco (http://dgarijo.github.io/Widoco/doc/bestPractices/index-en.html) and support the metadata attributes of MOD (http://www.lirmm.fr/~jonquet/publications/documents/Article_MTSR-2017_MOD1.2.pdf).

See also #29, #94, and #130, as well as https://github.com/ESIPFed/sweet/issues/54.

**Comment by lewismc** [comment]
Closing in preference for #130
