### ISSUE TITLE
LODE not doing well

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#133]
Clicking on IODE tab in COR or MMI ORR produces no response, or eventually, a 500 error. Also, the IODE link in the pre-calculated SWEET viewing pages doesn't produce anything useful. (The cached one looks OK.)  Seems like the service might be down?

**Comment by lewismc** [comment]
There is another service maintained by Nick Carr, I believe of CSIRO. I'll try to find out and we can adjust to the stable service. Please raise this at todays COR meeting.

**Comment by carueda** [comment]
And one other possibility (discussed in the past but I'm forgetting the channel/ticket) is to install LODE (or any other desirable "external" tool) on the COR machine itself. In particular, we would have less dependency on the external service availability.

**Comment by graybeal** [comment]
Simon mentions https://github.com/RDFLib/pyLODE.

**Comment by lewismc** [comment]
https://github.com/RDFLib/pyLODE/issues/23

**Comment by rduerr** [comment]
I note that while the COR LODE link does not work - links like http://150.146.207.114/lode/extract?url=http://cor.esipfed.org/ont/~rduerr/ADO&lang=en do work!

**Comment by lewismc** [comment]
LODE is broken. I think we should close this off and move on with pyLODE or something else as separate issues. Please re-open @graybeal if you disagree.
