### ISSUE TITLE
Add ability to update email of user's account

### ISSUE THREAD

**Issue by carueda** [mmisw/orr-portal#150]
It's possible to update one's name and phone number but not the email address.

**Comment by carueda** [comment]
Just verified that the backend does support updating the email as well: http://cor.esipfed.org/ontapi/#!/triplestore/unloadOntsInTriplestore

![image](https://user-images.githubusercontent.com/556505/66142966-432a4700-e5bb-11e9-80b4-8452d0b88cc3.png)

So, the needed adjustment is only here in the front-end (orr-portal).

**Comment by smrgeoinfo** [comment]
@carueda Thanks for looking into this

**Comment by carueda** [comment]
@smrgeoinfo sure, it's already implemented but still to be deployed.

**Comment by carueda** [comment]
@smrgeoinfo I just deployed the new version 3.8.8.  You may need to do a hard-reload in your browser.  When clicking my name on the top-right corner of the COR page this is how it looks in my case, where there's now an editable field for the email:

![image](https://user-images.githubusercontent.com/556505/66164102-c0b77c80-e5e6-11e9-80cb-85f7d62a31a7.png)
