### ISSUE TITLE
Upgrade gulp 3.9.1 --> 4.0.1

### ISSUE THREAD

**Issue by lewismc** [mmisw/orr-portal#161]
I wanted to use gulp to list all of the tasks which can be executed. This is usually done by executing 
```
gulp --list
```
This resulted in the issue described [here](https://www.sitepoint.com/pass-parameters-gulp-tasks/) and [here](https://stackoverflow.com/questions/52301415/gulp-assertionerror-err-assertion-task-function-must-be-specified?answertab=active#tab-top).
So I decided to go ahead and upgrade Gulp... PR coming up.

**Comment by lewismc** [comment]
@carueda I think we've got a regression on some of the previous logic. For example in `master` branch `gulp dev` is hanging again for me :(

**Comment by carueda** [comment]
`gulp dev` opens the app in my browser just fine. Maybe resync with master?

**Comment by carueda** [comment]
btw, let's close this one as gulp 4.0.2 is now in place

**Comment by carueda** [comment]
all seems to be ok when issuing gulp commands under the orr-portal codebase ... but for long while I've been fighting weird issues with such commands running as part of the docker image build ;(
