### ISSUE TITLE
Broken links for CF ontology

### ISSUE THREAD

**Issue by jessicaaustin** [mmisw/orr-portal#175]
We use MMISW as a viewer for CF standard names. At some point, it looks like the direct links to specific CF params were broken.

For example, https://mmisw.org/ont/cf/parameter/air_temperature returns Not Found.

You can go to https://mmisw.org/ont/cf/parameter and look at any link in the `Subject` column -- it looks like they're all broken.

Any way these links could be fixed? Thanks!

**Comment by carueda** [comment]
Hi @jessicaaustin Thanks for the heads-up!  Seems like the triple store was not repopulated upon a recent upgrade of the system, apologies.  I just triggered that step and all those (term) links should be back up.

Thanks again!

(btw, just thought I'd mention our CFSN browser in case you are not aware and may find it useful: https://mmisw.org/cfsn/ )

**Comment by jessicaaustin** [comment]
Thanks for the quick fix @carueda !

And no, I wasn't aware of the CFSN browser. That is useful, thanks.
