### ISSUE TITLE
resource type selection in ontology metadata

### ISSUE THREAD

**Issue by carueda** [mmisw/orr-portal#32]
The field is there, but not the traditional selection from http://mmisw.org/ont/mmi/resourcetype (instances of the ResourceType class).

**Comment by graybeal** [comment]
Not sure what this refers to -- the field is *where*?  As long as you understand it no need to explain for my benefit....

**Comment by carueda** [comment]
traditional selection:

![image](https://cloud.githubusercontent.com/assets/556505/16314172/80e10f5a-3931-11e6-988d-8d29dc8fd717.png)

ORR3 with no such selection yet:

![image](https://cloud.githubusercontent.com/assets/556505/16314245/c91ef8e0-3931-11e6-9687-7f96d5d541ed.png)

**Comment by carueda** [comment]
Looks like this:

![image](https://cloud.githubusercontent.com/assets/556505/16359719/d67844aa-3af4-11e6-9de5-453da6f86624.png)

So, similarly as with the previous system, there is a now button to select one of the instances of the class associated with the "resource type" property.

This has been implemented in a generic way so other properties can also be dispatched by just indicating them in a new 'valueSelections' section in the configuration. For example:

```js
var appConfig = {
  ...

  // (optional) allows to specify vocabularies from which to populate selection drop-down 
  // lists in metadata editing.
  valueSelections: {
    // Each key:obj entry indicates:
    //    key:                property URI
    //    obj.class:          class of the terms that can be selected as value for the property
    //    obj.sparqlEndpoint: (optional) alternative SPARQL endpoint to query for the terms

    "http://mmisw.org/ont/mmi/20081020/ontologyMetadata/hasResourceType": {
      class: "http://mmisw.org/ont/mmi/resourcetype/ResourceType",

      sparqlEndpoint: "http://mmisw.org/sparql"
    }
  },
```
