### ISSUE TITLE
organization manager

### ISSUE THREAD

**Issue by carueda** [mmisw/orr-portal#36]
Capture some sort of “organization manager” in the data model so only members with such role can edit the organization details (including membership list).

**Comment by carueda** [comment]
@graybeal any comments?

**Comment by graybeal** [comment]
Nice to have. As I recall, the way it works now is that any organization member can edit the details. I would say that's tolerable, but not a fully mature solution. 

Given the number of pieces needed to fix it (add the org role, show the org role on the org page, add the UI to change people's org role, add the code to check the org role before taking controlled action),  I'd put it into the "when we have more time/money" pile.

**Comment by carueda** [comment]
Thanks!  I will close this and mark it "revisit_later" (a label I came up with today as a strategy to clean up the tracker, but with some quick way to look again at entries like these at some point in the future).
