### ISSUE TITLE
Testing popup is offscreen left

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#40]
Testing popup is offscreen left

<img width="969" alt="screen shot 2016-07-04 at 3 49 04 pm" src="https://cloud.githubusercontent.com/assets/1266896/16574787/95efdcaa-4237-11e6-86d9-bfcadf3fc255.png">

**Comment by carueda** [comment]
Thanks.  Just reproduced this using Safari.

The "testing" popover is temporary, but the general styling/layout is not as intended in Safari. Will see what adjustment can be made that works without any browser-specific hack. 

As a general comments, all should work OK across modern versions of major browsers. Development/testing is mainly based on Chrome, where the overall (and intended) layout looks like this:

![image](https://cloud.githubusercontent.com/assets/556505/16598737/287c4d7a-42b4-11e6-960f-fb4b9e93164c.png)
