### ISSUE TITLE
updating metadata for an ontology doesn't show or maintain existing values

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#42]
When I updated the metadata for the SWEET ontology, it didn't show existing metadata, then deleted the existing when I submitted the update. 

<img width="1196" alt="screen shot 2016-07-04 at 4 25 57 pm" src="https://cloud.githubusercontent.com/assets/1266896/16574936/f3cfa6f6-4238-11e6-97d9-470a56a3b26e.png">

**Comment by carueda** [comment]
The properties are there but not showing up for some reason. A workaround is to force a browser page reload.

Still trying to reproduce locally ..

**Comment by carueda** [comment]
marking as fixed as could not reproduce either locally (both directly or via local docker deployment) or on COR.  Likely resolved by various adjustments.  v3.0.4.-alpha.
