### ISSUE TITLE
modal issues with parameter entry

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#43]
The entry of metadata attributes is problematic.

a) If I enter an attribute and hit return or tab, or click in another field, I expect the original field to auto-update and close. I don't want to have to hit Apply each time.
b) If I go to another page (or field) without having hit Apply, I can't edit the metadata there, and there is no clue as to what the problem is (I'm not even on the tab where the problem is). I don't think it should be a problem to have multiple fields open, but if it is, see (a) -- leaving the context is saying 'enter this data'.

<img width="1033" alt="screen shot 2016-07-04 at 8 14 59 pm" src="https://cloud.githubusercontent.com/assets/1266896/16574977/319d44ca-4239-11e6-8bdd-1865ce9eddd8.png">

**Comment by carueda** [comment]
New simplified editing handling of property values both on metadata and on vocabulary (v2r) table:

- Enter key and blur event immediately accept the cell contents
- only a single text area for the cell value is used (the previous multiple textareas would be tricky to handle along with the intended behaviour of automatically accepting the whole contents of the cell while navigating with tab or clicking outside of the cell)
- to still capture multiple values, the user can enter five dashes `-----` in a line by itself; this sequence serves as separator for a multi-valued cell.
- As in google spreadsheets, Ctrl-Enter can be used to enter a new line as part of a single value;
- Esc cancels changes in the cell

These adjustments look pretty acceptable to me so I'm closing this issue.  This can be re-opened if there are bugs associated with these adjustments as already described.  For further improvements let's open more specific issues later on.
