### ISSUE TITLE
metadata attribute help needs help

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#44]
Many of the metadata attributes have no useful explanation for their help tip. They just put up a URL, which *seems like* it would be helpful in some way but in fact isn't.  All the tips from the original should be brought over.

**Comment by carueda** [comment]
Copy-n-pasted the descriptions from the ORR v2 directly.

Please help review and provide revised texts when convenient.  In particular, the new system internally allows to indicate two variations per tooltip depending on whether the metadata is in view mode or in edit mode. 

For example, for `omv:Contributor`:

View mode:

> List of all the individuals and/or organizations that contributed materially to this vocabulary/ontology.

Edit mode:
    
> List of all the individuals and/or organizations that contributed materially to this vocabulary/ontology. You may use comma-separated names or URIs. This is a free text field.
