### ISSUE TITLE
autocomplete of browser not honored in term set class dialog

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#45]
If term set class dialog box name is apparently autocompleted in the browser, hitting the submit button doesn't fill out/accept the autocompletion. This is pretty minor but unexpected nonetheless.

<img width="1145" alt="screen shot 2016-07-04 at 8 16 25 pm" src="https://cloud.githubusercontent.com/assets/1266896/16575086/217ca35a-423a-11e6-9db6-948b481dbb19.png">

**Comment by carueda** [comment]
Not sure what this issue is about. Can you expand a bit, what browser are you using, etc?

The only browser driven autocompletion I expect is in the login dialog, but this is completely browser driven -- i.e., no application logic at all to enable this.

**Comment by graybeal** [comment]
Ah, let’s drop it. Not sure which browser and arguably I should expect the behavior (the browser showing the autocompletion, but not using it when I hit return).


On Jul 6, 2016, at 8:38 PM, Carlos Rueda <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure what this issue is about. Can you expand a bit, what browser are you using, etc?

The only browser driven autocompletion I expect is in the login dialog, but this is completely browser driven -- i.e., no application logic at all to enable this.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://github.com/mmisw/orr-portal/issues/45#issuecomment-230970876>, or mute the thread<https://github.com/notifications/unsubscribe/ABNU0D_IX_RhTla98JzyvBBoR6Uhsv-yks5qTHTEgaJpZM4JEzDN>.

========================
John Graybeal
Technical Program Manager
Center for Expanded Data Annotation and Retrieval /+/ NCBO BioPortal
Stanford Center for Biomedical Informatics Research
650-736-1632
skype: graybealski
