### ISSUE TITLE
really don't like ~ in owner URIs

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#46]
I really don't like the ~ in the owner URIs. In addition to being a major pain to type -- so that I would try to become an organization or create my own URLs instead, if I had to -- it creates some confusion vs the regular URIs, and makes the owner ontologies seem a little less valuable. 

I strong prefer just treating owners and organizations the same, and monitoring the list of owners and organizations so that duplicates are caught when they are created. I know that will create a scaleability issue someday, but I think it's worth it to make sure we get to that day.

**Comment by carueda** [comment]
>I really don't like the ~ in the owner URIs. In addition to being a major pain to type -- so that I would try to become an organization or create my own URLs instead, if I had to -- it creates some confusion vs the regular URIs, and makes the owner ontologies seem a little less valuable.

Exactly part of the reason I decided to add the extra burden: To discourage ontology ownership by users! This could of course be better documented. We should probably get other opinions before changing this.

> I strong prefer just treating owners and organizations the same, and monitoring the list of owners and organizations so that duplicates are caught when they are created. I know that will create a scaleability issue someday, but I think it's worth it to make sure we get to that day.

Yeah, let's revisit this later.

**Comment by graybeal** [comment]
Why do we want to discourage ontology ownership by users?

John

On Jul 5, 2016, at 1:53 PM, Carlos Rueda <notifications@github.com<mailto:notifications@github.com>> wrote:


I really don't like the ~ in the owner URIs. In addition to being a major pain to type -- so that I would try to become an organization or create my own URLs instead, if I had to -- it creates some confusion vs the regular URIs, and makes the owner ontologies seem a little less valuable.

Exactly part of the reason I decided to add the extra burden: To discourage ontology ownership by users! This could of course be better documented. We should probably get other opinions before changing this.

I strong prefer just treating owners and organizations the same, and monitoring the list of owners and organizations so that duplicates are caught when they are created. I know that will create a scaleability issue someday, but I think it's worth it to make sure we get to that day.

Yeah, let's revisit this later.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/mmisw/orr-portal/issues/46#issuecomment-230599779>, or mute the thread<https://github.com/notifications/unsubscribe/ABNU0JxRikdb3uKdvSTP5XR6lb7kTJerks5qSsROgaJpZM4JEzLC>.

========================
John Graybeal
Technical Program Manager
Center for Expanded Data Annotation and Retrieval /+/ NCBO BioPortal
Stanford Center for Biomedical Informatics Research
650-736-1632
skype: graybealski

**Comment by carueda** [comment]
Let me put it in a positive way: ownership by users is OK, but ontology ownership by organizations is encouraged in general.  My motivation for this relies on trust: As a visitor or someone searching for ontologies, I would in general have a better (or more immediate) sense of trust when there's an organization behind the ontologies I find.  There certainly are a number of other factors for trust but that was my motivation.

**Comment by graybeal** [comment]
Certainly true. Whether we should make that point by making personal ontologies appear less appealing is not so clear. 

Nonetheless, it disambiguates personal ontologies in a clear way, and we will hear from users (presumably) if they find the approach unacceptable. So let's consider this closed/won't fix for now.
