### ISSUE TITLE
term set class dialog box help text context issue

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#47]
The description that goes with the workflow of this dialog box isn't in the right context. We frame it in terms of the creation of the URI, but the user has no way to understand what the relationship of the URI sub-part is to the class name.

The thing that the user is doing, and that the user should understand, is creating a class name for the type of terms he or she is creating (in that term set).  So the description should be "Define the name of the class that describes the type of terms you are creating (like the column header or name of the vocabulary). Note that this name will be used to build the URI for the class, so it should not have any special characters." (Is camel case appropriate? I'm not sure I remember any more, but thought it was recommended)

<img width="1145" alt="screen shot 2016-07-04 at 8 16 25 pm" src="https://cloud.githubusercontent.com/assets/1266896/16575215/5072c008-423b-11e6-896c-72a93a6c2056.png">

**Comment by carueda** [comment]
![image](https://cloud.githubusercontent.com/assets/556505/16641714/220d908e-43b8-11e6-9457-124f977889ce.png)
