### ISSUE TITLE
URIs should be IRIs

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#48]
I think we are in a brave new world and they aren't called URIs any more, they are called IRIs. If they are nicely internationalized they are, anyway. This shows up throughout the dialogs. (Sorry!)

**Comment by carueda** [comment]
Agree .. and it's actually been in my todo list for a long time ...  but I hope we can defer on this while I stable version is in place (2nd year of XDOMEs..)

**Comment by graybeal** [comment]
oh-kay…

On Jul 6, 2016, at 10:53 PM, Carlos Rueda <notifications@github.com<mailto:notifications@github.com>> wrote:


Agree .. and it's actually been in my todo list for a long time ... but I hope we can defer on this while I stable version is in place (2nd year of XDOMEs..)

**Comment by carueda** [comment]
Summary of changes in RDF 1.1, which uses IRIs - https://www.w3.org/TR/rdf11-new/#identifiers

**Comment by carueda** [comment]
I have completed most of the necessary changes in the backend (https://github.com/mmisw/orr-ont/pull/49), which will get exposed in version 3.6.0, and will looking into the corresponding changes for the UI.
