### ISSUE TITLE
mappings didn't work

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#52]
I selected a few ontologies and tried to map a few terms, but couldn't see that anything was happening. I might have gotten one mapping to work, but that was it.

Also wasn't clear what the 2nd row from the bottom of the page was, that looked like 3 empty fields to fill in. Could be useful I'm guessing, but I'm not sure how.

**Comment by carueda** [comment]
I'm not really aware of any significant issues with the mapping tool.  Please provide more details when you get a chance.

**Comment by carueda** [comment]
Ah! forgot about this, and since it was not marked bug, I missed to notice it;  anyway simply closing as duplicate of #56
