### ISSUE TITLE
Create organization dialog box URI not right?

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#53]
In the create organization dialog box, the URI says http://cor.esipfed.org/ont3/org/<short-name>. But I think the short name goes where it says 'org'. Oh! Wait, you're making a URI *for* the organization, aren't you? That wasn't clear, sorry.

It's worth a note too to say "the short name will be used in the IRIs of the vocabularies created for this organization".

![Uploading Screen Shot 2016-07-04 at 11.18.44 PM.png…]()

**Comment by carueda** [comment]
Sorry, that URL field there was a bad copy-n-paste.  It is now removed (in 3.0.4-alpha).

That interface looks now as follows:

![image](https://cloud.githubusercontent.com/assets/556505/16643235/871ef7f6-43c7-11e6-800e-f0840a9826ea.png)

Note, there's now a field for a user-given URL for the organization.
