### ISSUE TITLE
count of checked boxes wrong in mapper

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#59]
In mapping tool, select 1 or 2 individual mappings. Then click on select all. The total number of selected mappings will be the same as the total number of available mappings, even though the previously selected individual mappings have been unselected. (Reselecting them increases the previous number, so now you have more mappings 'selected' than there are mappings.)

![screen shot 2016-07-13 at 10 50 37 pm](https://cloud.githubusercontent.com/assets/1266896/16829378/b50f437a-494c-11e6-800b-699f7b0cfbb8.png)

**Comment by carueda** [comment]
Thanks for reporting, will take a closer look later but just trying to quickly reproduce right now"

>In mapping tool, select 1 or 2 individual mappings.

![image](https://cloud.githubusercontent.com/assets/556505/16844633/c0cd60a4-499a-11e6-92f0-5177d7d46e82.png)

ok.

> Then click on select all

![image](https://cloud.githubusercontent.com/assets/556505/16844661/d495dfda-499a-11e6-8958-6e3b75c19069.png)

>The total number of selected mappings will be the same as the total number of available mappings,

yes, ok.

>even though the previously selected individual mappings have been unselected. 

Don't follow here ... I see all 7 selected as expected.

>(Reselecting them increases the previous number, so now you have more mappings 'selected' than there are mappings.)

Wanted to do this step, but all 7 are selected for me at this point (?).

**Comment by graybeal** [comment]
try it in Safari. And try using just the first two buttons. The key difference is that when I clicked on Select all, the previously checked boxes became unchecked. If that doesn't happen, you can't duplicate it.

________________________________

**Comment by carueda** [comment]
No, that doesn't happen. Just tried with Safari.
