### ISSUE TITLE
ENVO ontology

### ISSUE THREAD

**Issue by carueda** [mmisw/orr-portal#62]
Fails to load.

![image](https://cloud.githubusercontent.com/assets/556505/17000564/19cd16d6-4e91-11e6-919d-103b852c23bb.png)

@graybeal FYI

**Comment by carueda** [comment]
[John's email 7/20]

>There are some issues with the latest submission of ENVO to Stanford’s BioPortal, and it may be that the latest one is in ESIP’s BioPortal. In which case, the error would likely be with ENVO.  
>
>In any case, ENVO is an OBO ontology, which is format not supported by MMI. So it could not be uploaded directly to COR. I have taken the last valid ENVO XML/RDF version in BioPortal, and when I upload it (signature is .xrdf) the upload finishes but the Next button does not become enabled. Changed the extension to .rdf, same result. So that’s over to you to take a look, see if it’s obvious why the ENVO downloads are failing. 
>
>(The test case around here is to open with Protege. If that fails, ontology is typically bad.)
>
>I can say that the conversion from OBO to OWL or RDF/XML typically produces some weirdness, like this section:
>    ```xml
>    <ObjectProperty rdf:about="http://purl.obolibrary.org/obo/BFO_0000055”>
>      <rdfs:label   rdf:datatype="http://www.w3.org/2001/XMLSchema#string">realizes</rdfs:label>
>      <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Paraphrase of elucidation: a relation between a process and a realizable entity, where there is some material entity that is bearer of the realizable entity and participates in the process, and the realizable entity comes to be realized in the course of the process</rdfs:comment>
>      <obo:IAO_0000111 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">realizes</obo:IAO_0000111>
>      <obo:IAO_0000112 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">this disease course realizes this disease</obo:IAO_0000112>
>      <obo:IAO_0000112 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">this investigation realizes this investigator role</obo:IAO_0000112>
>      <obo:IAO_0000112 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">this shattering realizes this fragility</obo:IAO_0000112>
>    ```
>I can’t even tell what that might mean.
>
>There are also some issues with the installation of the ESIP BioPortal, so that some of its links to download ontologies may not be working. That’s keeping me from testing the ICEOFLANDORIGIN ontology submitted there. I’m contacting Line to find out who the right technical person is for me to coordinate with. Meanwhile, if we can get a copy of the original ontology from Margaret or Ruth, that would be a better thing to try at this moment. 
>
>I may have made a contribution of ICEOFLANDORIGIN in the ORR repository for Ruth some time ago, so you might be able to pull it from there. (Actually 2 contributions, one as remote hosted and one as local hosted.) Not sure if that’s the one I did though — likely it was wmo_seaice, which is probably different.)
>
>John

**Comment by carueda** [comment]
@graybeal I’m not familiar with the ENVO ontology myself but just found https://www.ebi.ac.uk/ols/ontologies/envo , from which I can get to http://www.berkeleybop.org/ontologies/envo/, where there is an RDF/XML representation available (envo.owl).

Can you confirm that’s the ENVO ontology we are looking at here?  If not, I can ask Margaret.

**Comment by graybeal** [comment]
I expect it is. I’m sure there’s only one ENVO ontology in OBO.

john

On Jul 26, 2016, at 10:40 AM, Carlos Rueda <notifications@github.com<mailto:notifications@github.com>> wrote:


@graybeal<https://github.com/graybeal> I’m not familiar with the ENVO ontology myself but just found https://www.ebi.ac.uk/ols/ontologies/envo , from which I can get to http://www.berkeleybop.org/ontologies/envo/, where there is an RDF/XML representation available (envo.owl).

Can you confirm that’s the ENVO ontology we are looking at here? If not, I can ask Margaret.

**Comment by carueda** [comment]
Closing this issue as I just registered this ontology with no issues at all (using latest ORR 3.1.7 at COR, http://cor.esipfed.org/ont).  

The steps:

- From https://www.ebi.ac.uk/ols/ontologies/envo  I clicked Downloaded the file (`envo.owl`).
- √ Using the ORR Upload option I entered the file and got uploaded after a few seconds (it's a 8.5MB file). 
- √ ORR suggested the URI `http://purl.obolibrary.org/obo/envo.owl` as extracted from the file.
- √ Registration completed normally.  http://cor.esipfed.org/ont?uri=http://purl.obolibrary.org/obo/envo.owl

Note: the original ontology metadata includes rather strange comments that are simply reflected in the ORR interface:

![2017-02-03_2142](https://cloud.githubusercontent.com/assets/556505/22616053/fece02ea-ea59-11e6-8121-3f1da72607ca.png)

The corresponding snippet from the file:

```xml
    <owl:Ontology rdf:about="http://purl.obolibrary.org/obo/envo.owl">
        <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/envo/releases/2017-01-07/envo.owl"/>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Includes Ontology(OntologyID(OntologyIRI(&lt;http://purl.obolibrary.org/obo/envo/imports/imports/ncbitaxon_import.owl&gt;) VersionIRI(&lt;null&gt;))) [Axioms: 261 Logical Axioms: 56]</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Includes Ontology(OntologyID(OntologyIRI(&lt;http://purl.obolibrary.org/obo/envo/modules/process_attribute.owl&gt;) VersionIRI(&lt;null&gt;))) [Axioms: 20 Logical Axioms: 2]</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Includes Ontology(OntologyID(OntologyIRI(&lt;http://purl.obolibrary.org/obo/envo/imports/ro_import.owl&gt;) VersionIRI(&lt;null&gt;))) [Axioms: 1092 Logical Axioms: 264]</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Includes Ontology(OntologyID(OntologyIRI(&lt;http://purl.obolibrary.org/obo/envo/imports/pato_import.owl&gt;) VersionIRI(&lt;null&gt;))) [Axioms: 703 Logical Axioms: 267]</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Includes Ontology(OntologyID(OntologyIRI(&lt;http://purl.obolibrary.org/obo/envo/imports/pco_import.owl&gt;) VersionIRI(&lt;null&gt;))) [Axioms: 21 Logical Axioms: 3]</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Includes Ontology(OntologyID(OntologyIRI(&lt;http://purl.obolibrary.org/obo/envo/modules/entity_attribute_location.owl&gt;) VersionIRI(&lt;null&gt;))) [Axioms: 119 Logical Axioms: 20]</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ENVO is an ontology which represents knowledge about environments,environmental processes, ecosystems, habitats, and related entities. It interoperates with other ontologies in the OBO Foundry and Library. Please see www.environmentontology.org for more info.</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Includes Ontology(OntologyID(OntologyIRI(&lt;http://purl.obolibrary.org/obo/envo/modules/entity_attribute.owl&gt;) VersionIRI(&lt;null&gt;))) [Axioms: 50 Logical Axioms: 7]</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Includes Ontology(OntologyID(OntologyIRI(&lt;http://purl.obolibrary.org/obo/envo/imports/chebi_import.owl&gt;) VersionIRI(&lt;null&gt;))) [Axioms: 2398 Logical Axioms: 1010]</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Includes Ontology(OntologyID(OntologyIRI(&lt;http://purl.obolibrary.org/obo/envo/imports/imports/po_import.owl&gt;) VersionIRI(&lt;null&gt;))) [Axioms: 94 Logical Axioms: 9]</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Includes Ontology(OntologyID(OntologyIRI(&lt;http://purl.obolibrary.org/obo/envo/imports/go_import.owl&gt;) VersionIRI(&lt;null&gt;))) [Axioms: 85 Logical Axioms: 18]</rdfs:comment>
        <oboInOwl:default-namespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ENVO</oboInOwl:default-namespace>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Includes Ontology(OntologyID(OntologyIRI(&lt;http://purl.obolibrary.org/obo/envo/imports/bfo_import.owl&gt;) VersionIRI(&lt;null&gt;))) [Axioms: 34 Logical Axioms: 7]</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Includes Ontology(OntologyID(OntologyIRI(&lt;http://purl.obolibrary.org/obo/envo/modules/entity_quality_location.owl&gt;) VersionIRI(&lt;null&gt;))) [Axioms: 45 Logical Axioms: 6]</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Includes Ontology(OntologyID(OntologyIRI(&lt;http://purl.obolibrary.org/obo/envo/imports/pco_bfo_bridge.owl&gt;) VersionIRI(&lt;null&gt;))) [Axioms: 3 Logical Axioms: 1]</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Includes Ontology(OntologyID(OntologyIRI(&lt;http://purl.obolibrary.org/obo/envo/imports/uberon_import.owl&gt;) VersionIRI(&lt;null&gt;))) [Axioms: 24168 Logical Axioms: 4726]</rdfs:comment>
    </owl:Ontology>
```

@graybeal FYI
