### ISSUE TITLE
SPARQL portal not responding

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#63]
On Jul 20, 2016, at 10:05, Mcgibbney, Lewis J (398M) via esip-semanticweb <esip-semanticweb@lists.esipfed.org> wrote:

Hi Folks,
Is anyone currently using the SPARQL API functionality of the portal?

Reading the docs @ [0], I see that an endpoint should be available at
http://cor.esipfed.org/sparql, however it does not render in a browser.
Firebug indicates that a bunch of CSS, JS and IMG/GIF imports are not
available.

[0] https://mmisw.github.io/mmiorr-docs/query/

**Comment by carueda** [comment]
cor.esipfed.org/sparql *is* indeed the programmatic SPARQL endpoint, not a
UI.

For the UI, go to http://cor.esipfed.org/ont/sparql (which is linked to in
the "search terms" option in the main portal UI, http://cor.esipfed.org/ont/
.

**Comment by graybeal** [comment]
verified this works. closing issue.

**Comment by carueda** [comment]
Thanks John.

However, adding a more explicit "Advance Search" option, next to the current "Search Terms" one, would be good.  Any other suggestion eg. about name of the option (perhaps "SPARQL Search"), etc?

**Comment by graybeal** [comment]
Depends on what it leads to. If just the SPARQL UI, I think SPARQL Search is most direct.


On Jul 27, 2016, at 8:18 AM, Carlos Rueda <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks John.

However, adding a more explicit "Advance Search" option, next to the current "Search Terms" one, would be good. Any other suggestion eg. about name of the option (perhaps "SPARQL Search"), etc?

**Comment by carueda** [comment]
done. will show up in 3.0.3-beta
