### ISSUE TITLE
better display of regular ontology

### ISSUE THREAD

**Issue by carueda** [mmisw/orr-portal#68]
Currently, ontologies _not_ built with the ORR tools are dispatched in a rather simple way: in a 3-column table corresponding to the triples in the ontology.

So, this is about exploring and incorporating a better display mechanism, ideally with a tool that can be easily embedded.   (Note, this task is _not_ about editing as this is out of the scope of the ORR.)
- Possible options (not necessarily mutually exclusive):
- Our own [orrv](https://github.com/mmisw/orrv) prototype, which with the MMI Device Ontology looks like shown in this link: http://mmisw.org/experimental/orrv/#/uri/http://mmisw.org/ont/mmi/device
- http://vowl.visualdataweb.org/webvowl is a very interesting graphical tool. With the  MMI Device Ontology: http://vowl.visualdataweb.org/webvowl/index.html#iri=http://mmisw.org/ont/mmi/device looks like this:

![image](https://cloud.githubusercontent.com/assets/556505/17796894/1af1b72a-6579-11e6-9cb1-9257b3384519.png)

**Comment by carueda** [comment]
Added configuration entry to indicate external ontology viewers than can be dispatched with the ontology URI in a parameter. At the moment with the VOWL tool in the master configuration.  This can be disabled/extended/overwritten in the `local.config.js` file as needed.

```js
  externalTools: {
    // ontViewers: List of external ontology browsers/visualizers.
    // These will be shown as options to display ontologies not created by the ORR.
    // They are are dispatched in an iframe.
    // Use `$uri` to refer to the ontology URI in srcUrlTemplate.
    ontViewers: [
      {
        name: 'WebVOWL',
        title: 'Web-based Visualization of Ontologies',
        srcUrlTemplate: 'http://vowl.visualdataweb.org/webvowl/index.html#iri=$uri',
        moreInfoUrl: 'http://vowl.visualdataweb.org/webvowl.html'
      }
    ]
  },
```
The default display is with the built-in "triple table" as before.  With the VOWL option looks like this:

![2016-10-28_2120](https://cloud.githubusercontent.com/assets/556505/19827138/751a0514-9d54-11e6-829a-7acc6a5f7725.png)

It would be better to have a local deployment of the VOWL tool (including the required conversion tool OWL2VOWL) so as not to depend on the availability of the external service. But this would require some work.  Let's see how it goes for the time being.

**Comment by carueda** [comment]
With the addition of LODE (#83) I'm closing this one.

I'm not saying that this is a perfect solution, but seems like at least acceptable for the time being.

Let's just open other entries in case of more specific issues/needs.

**Comment by carueda** [comment]
I'm reopening this entry with the idea of actually having local installations of (at least, initially) the LODE and VOWL tools.  The already existing mechanism to enable such tools won't need to be changed. We could first tests things on any of our "controlled" ORR instances (COR, in particular), and then perhaps create and use docker images for such tools to facilitate their deployment for other instances.

**Comment by lewismc** [comment]
ack @carueda this would provide better functionality for COR users for sure.

**Comment by lewismc** [comment]
@carueda I'm not sure if this issue should be kept open any more. Although it takes a while, LODE does work. Unless we run an instance of LODE as a docker container alongside the existing deployment then we simply need to accept external dependency on LODE (or whatever else someone wishes to configure in the future).

**Comment by carueda** [comment]
@lewismc  Thanks, yes it makes sense to close this one.

Well, mainly because:
- there's configurability in the ORR to point to external services
- so, each concrete ORR instance (like COR) can decide which external tools to "integrate"

Now, re specific tools, it would be convenient to have local installations of them to avoid relaying on the external service, which could probably be over-loaded if exercised from many places, etc.

Besides, LODE, it would be good to revisit VOWL.
