### ISSUE TITLE
No response from 'Get ontologies of a given organization' REST endpoint

### ISSUE THREAD

**Issue by lewismc** [mmisw/orr-portal#74]
Hi Folks,
I'm currently designing some application code which I want to interact with the COR deployed at http://cor.esipfed.org/ont.
So far I am really enjoying the REST API but have just run into something which I think best to report.
When attempting to obtain an organization all is good
```
lmcgibbn@LMC-056430 /usr/local $ GET /api/v0/org/w3c
{"orgName":"w3c","name":"The World Wide Web Consortium","url":"https://www.w3.org/"}
lmcgibbn@LMC-056430 /usr/local $ GET /api/v0/org/esip
{"orgName":"esip","name":"ESIP Federation","url":"http://esipfed.org/"}
```
The issue I have is that I cannot then obtain all the ont resources for one of those organizations as follows
```
lmcgibbn@LMC-056430 /usr/local $ GET /api/v0/ont\?orgName=w3c
```
AFAICT the following resource should be returned http://cor.esipfed.org/ont/?uri=https://www.w3.org/ns/ssn
Am I using the API incorrectly here? I am following the documentation available at https://github.com/mmisw/orr-ont/wiki/basic-interaction#get-ontologies-of-a-given-organization

Thanks for any convo on this one.

**Comment by lewismc** [comment]
Actually the same seems to happen if I attempt to obtain an ont resource for a specific URI e.g. 
```
lmcgibbn@LMC-056430 /usr/local $ GET /api/v0/ont\?uri=https://www.w3.org/ns/ssn\&format=n3
```
I get no response either. On this occasion I am following the documentation available at https://github.com/mmisw/orr-ont/wiki/basic-interaction#get-an-ontology-in-a-particular-format.

Thanks for any help here.

**Comment by carueda** [comment]
Hi Lewis,

The https://github.com/mmisw/orr-ont/wiki/basic-interaction wiki needs to be updated, sorry.

> The issue I have is that I cannot then obtain all the ont resources for one of those organizations as follows
> 
>     lmcgibbn@LMC-056430 /usr/local $ GET /api/v0/ont\?orgName=w3c
> 
> 

Instead of `orgName`, please use the `ownerName` parameter, e.g.:

```
$ http get 'http://cor.esipfed.org/ont/api/v0/ont?ownerName=w3c'
HTTP/1.1 200
Access-Control-Allow-Origin: *
Connection: close
Content-Length: 254
Content-Type: application/json;charset=UTF-8
Date: Wed, 05 Oct 2016 15:27:16 GMT
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
X-XSS-Protection: 1; mode=block

[
    {
        "author": "The World Wide Web Consortium",
        "format": "rdf",
        "name": "Semantic Sensor Network Ontology",
        "ownerName": "w3c",
        "status": "unstable",
        "uri": "https://www.w3.org/ns/ssn",
        "version": "20160705T060854",
        "visibility": "public"
    }
]
```

This reflects a more recent change in the underlying model, which allows an ontology to be owned either by an organization (like the case above), or by a user. In the case of a user, use [`~`](https://github.com/mmisw/orr-portal/issues/46) in front of the corresponding username for the `ownerName` value, e.g.:

```
http get 'http://cor.esipfed.org/ont/api/v0/ont?ownerName=~lmcgibbn'
HTTP/1.1 200
Access-Control-Allow-Origin: *
Connection: close
Content-Length: 251
Content-Type: application/json;charset=UTF-8
Date: Wed, 05 Oct 2016 15:32:49 GMT
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
X-XSS-Protection: 1; mode=block

[
    {
        "author": "Lewis McGibbney",
        "format": "rdf",
        "name": "SWEET Ontology",
        "ownerName": "~lmcgibbn",
        "status": "stable",
        "uri": "http://sweet.jpl.nasa.gov/2.3/humanAgriculture.owl",
        "version": "20160720T183818",
        "visibility": "public"
    }
]
```

> ... the same seems to happen if I attempt to obtain an ont resource for a specific URI e.g.
> 
> lmcgibbn@LMC-056430 /usr/local $ GET /api/v0/ont\?uri=https://www.w3.org/ns/ssn\&format=n3
> I get no response either. 
> 

Not sure how you are setting the URL prefix for your requests ... but this works:

```
http get 'http://cor.esipfed.org/ont/api/v0/ont?uri=https://www.w3.org/ns/ssn&format=n3'
HTTP/1.1 200
Access-Control-Allow-Origin: *
Connection: close
Content-Type: text/n3;charset=UTF-8
Date: Wed, 05 Oct 2016 15:44:04 GMT
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
X-XSS-Protection: 1; mode=block

@base          <https://www.w3.org/ns/ssn> .
@prefix dc:    <http://purl.org/dc/elements/1.1/> .
@prefix :      <https://www.w3.org/ns/ssn/> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ns:    <http://creativecommons.org/ns#> .
@prefix terms: <http://purl.org/dc/terms/> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

:SurvivalRange  a        owl:Class ;
        rdfs:comment     "The conditions a sensor can be exposed to without damage: i.e., the sensor continues to operate as defined using MeasurementCapability.  If, however, the SurvivalRange is exceeded, the sensor is 'damaged' and MeasurementCapability specifications may no longer hold." ;

...
```

Hope this clarifies things a bit.  I'll take an action to update the mentioned wiki page, and, as you probably already know, we still have some good work to do on the general documentation (http://mmisw.org/orrdoc/).  Please keep your feedback coming!

**Comment by carueda** [comment]
BTW, the REST API documentation is being "captured" at http://mmisw.org/orrdoc/api/

**Comment by carueda** [comment]
Updated https://github.com/mmisw/orr-ont/wiki/basic-interaction with a note about contents not necessarily reflecting latest changes in parameters/operations/model/etc, and, more importantly, pointing to "official" documentation at https://mmisw.org/orrdoc/.

**Comment by lewismc** [comment]
Thank you @carueda :)
