### ISSUE TITLE
nicer LOD-friendly display of content on ontology page

### ISSUE THREAD

**Issue by carueda** [mmisw/orr-portal#92]
In old system: https://github.com/mmisw/mmiorr/issues/326

> From jbgrayb...@mindspring.com on August 22, 2014 11:48:20
> 
> What capability do you want added or improved?
> 
> I want to improve the display of the ontology and metadata (see also issue #146 and issue #327 ), particularly values shown within the table. First priority is to provide auto-recognition of things that can be linked:
>
> - Link classes and terms to their page in ORR
> - URLs within the ontology auto-linked
> - URLs elsewhere auto-linked
> - Codes or Terms within the ontology auto-linked, to resolve on the appropriate ORR term page (see other details below)
> 
> What is the desired output (content, format, location)?
> 
> Following [CFSN](http://mmisw.org/cfsn/) format
> 
> Other details of your desired capability?
> 
> Later it would be cool to do CFSN's _ term recognition for searching, but recognizing more types of terms:
> 
> ASCII linked by _
> ASCII with embedded camelCase
> ASCII preceded by _
> hex IDs: 6 or more hex digits in a row
>

**Comment by graybeal** [comment]
Is this done, with the pyLODE feature available?

**Comment by carueda** [comment]
I dunno ; ) (you entered this -- in the old system as indicated). 

@lewismc  wdyt?

**Comment by lewismc** [comment]
Yes I think this is done ✅
-- 

*Lewis*
Dr. Lewis J. McGibbney Ph.D, B.Sc
*Skype*: lewis.john.mcgibbney
